
[App]
  env = "dev"
  host = "localhost"
  port = 7000

[[Proxy]]
  host = "localhost"
  hostname = "localhost:5070"
  port = 6000
  protocol = "http"

  [Proxy.Auth]
    htDigestFile = "htdigest"
    realm = "RPTAT"

  [Proxy.Metrics]
    max_pending = 0
    periodic_sync_interval = 30

  [Proxy.Store]
    file_name = "sample.json"
    file_perms = 420

[[Proxy]]
  host = "localhost"
  hostname = "localhost:5071"
  port = 6001
  protocol = "http"

  [Proxy.Auth]
    htDigestFile = "htdigest"
    realm = "RPTAT"

  [Proxy.Metrics]
    max_pending = 0
    periodic_sync_interval = 45

  [Proxy.Store]
    file_name = "notes.json"
    file_perms = 420
