
[App]
  env = "dev"
  host = "localhost"
  port = 7000

[[Proxies]]
  host = "localhost"
  hostname = "localhost:5070"
  port = 6000
  protocol = "http"

  [Proxies.Metrics]
    max_pending = 1
    periodic_sync_interval = 30

  [Proxies.Store]
    file_name = "sample.json"
    file_perms = 420

[[Proxies]]
  host = "localhost"
  hostname = "localhost:5071"
  port = 6001
  protocol = "http"

  [Proxies.Metrics]
    max_pending = 51
    periodic_sync_interval = 45

  [Proxies.Store]
    file_name = "notes.json"
    file_perms = 420
