
[API]
  host = "localhost"
  port = "8050"

[App]
  env = "dev"

[Metrics]
  max_pending = 0
  periodic_sync_interval = 30

[Proxy]
  host = "localhost"
  hostname = "localhost:7000"
  port = 6000
  protocol = "http"

[Store]
  file_name = "data.json"
  file_perms = 420
